// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom-chars': string;
  'bottom-chars__item': string;
  'bottomChars': string;
  'bottomCharsItem': string;
  'right-numbers': string;
  'right-numbers__item': string;
  'rightNumbers': string;
  'rightNumbersItem': string;
}
export const cssExports: CssExports;
export default cssExports;
