// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'piece': string;
  'pieceWrapper': string;
  'piece_wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
