// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'cell-active': string;
  'cell-possible-move': string;
  'cellActive': string;
  'cellBlack': string;
  'cellPossibleMove': string;
  'cellWhite': string;
  'cell_black': string;
  'cell_white': string;
  'piece-img': string;
  'pieceImg': string;
}
export const cssExports: CssExports;
export default cssExports;
