// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info-block': string;
  'info-block__current-turn': string;
  'infoBlock': string;
  'infoBlockCurrentTurn': string;
}
export const cssExports: CssExports;
export default cssExports;
