// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form-button': string;
  'form-decription': string;
  'formButton': string;
  'formDecription': string;
}
export const cssExports: CssExports;
export default cssExports;
