enum BOX_COLOR {
  WHITE = "white-box",
  BLACK = "black-box",
}

interface IChess {
  [key: string]: BOX_COLOR;
}

export const CHESS_MAP: IChess = {
  a8: BOX_COLOR.BLACK,
  b8: BOX_COLOR.WHITE,
  c8: BOX_COLOR.BLACK,
  d8: BOX_COLOR.WHITE,
  e8: BOX_COLOR.BLACK,
  f8: BOX_COLOR.WHITE,
  g8: BOX_COLOR.BLACK,
  h8: BOX_COLOR.WHITE,

  a7: BOX_COLOR.WHITE,
  b7: BOX_COLOR.BLACK,
  c7: BOX_COLOR.WHITE,
  d7: BOX_COLOR.BLACK,
  e7: BOX_COLOR.WHITE,
  f7: BOX_COLOR.BLACK,
  g7: BOX_COLOR.WHITE,
  h7: BOX_COLOR.BLACK,

  a6: BOX_COLOR.BLACK,
  b6: BOX_COLOR.WHITE,
  c6: BOX_COLOR.BLACK,
  d6: BOX_COLOR.WHITE,
  e6: BOX_COLOR.BLACK,
  f6: BOX_COLOR.WHITE,
  g6: BOX_COLOR.BLACK,
  h6: BOX_COLOR.WHITE,

  a5: BOX_COLOR.WHITE,
  b5: BOX_COLOR.BLACK,
  c5: BOX_COLOR.WHITE,
  d5: BOX_COLOR.BLACK,
  e5: BOX_COLOR.WHITE,
  f5: BOX_COLOR.BLACK,
  g5: BOX_COLOR.WHITE,
  h5: BOX_COLOR.BLACK,

  a4: BOX_COLOR.BLACK,
  b4: BOX_COLOR.WHITE,
  c4: BOX_COLOR.BLACK,
  d4: BOX_COLOR.WHITE,
  e4: BOX_COLOR.BLACK,
  f4: BOX_COLOR.WHITE,
  g4: BOX_COLOR.BLACK,
  h4: BOX_COLOR.WHITE,

  a3: BOX_COLOR.WHITE,
  b3: BOX_COLOR.BLACK,
  c3: BOX_COLOR.WHITE,
  d3: BOX_COLOR.BLACK,
  e3: BOX_COLOR.WHITE,
  f3: BOX_COLOR.BLACK,
  g3: BOX_COLOR.WHITE,
  h3: BOX_COLOR.BLACK,

  a2: BOX_COLOR.BLACK,
  b2: BOX_COLOR.WHITE,
  c2: BOX_COLOR.BLACK,
  d2: BOX_COLOR.WHITE,
  e2: BOX_COLOR.BLACK,
  f2: BOX_COLOR.WHITE,
  g2: BOX_COLOR.BLACK,
  h2: BOX_COLOR.WHITE,

  a1: BOX_COLOR.WHITE,
  b1: BOX_COLOR.BLACK,
  c1: BOX_COLOR.WHITE,
  d1: BOX_COLOR.BLACK,
  e1: BOX_COLOR.WHITE,
  f1: BOX_COLOR.BLACK,
  g1: BOX_COLOR.WHITE,
  h1: BOX_COLOR.BLACK,
};
