// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'game-page': string;
  'game-page__box': string;
  'gamePage': string;
  'gamePageBox': string;
}
export const cssExports: CssExports;
export default cssExports;
