// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'username-field': string;
  'usernameField': string;
}
export const cssExports: CssExports;
export default cssExports;
